version: '3.8'

services:
  consul:
    image: hashicorp/consul:latest
    ports:
      - "8500:8500"
    command: consul agent -dev -client=0.0.0.0
    networks:
      - app-network

  gateway:
    build:
      context: .
      dockerfile: gateway/Dockerfile
    ports:
      - "8084:8084"
    depends_on:
      - consul
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    networks:
      - app-network

  leader:
    build:
      context: .
      dockerfile: kv-node/Dockerfile
    ports:
      - "8080:8080"
    container_name: leader
    environment:
      - SPRING_PROFILES_ACTIVE=leader
    networks:
      - app-network

  worker1:
    build:
      context: .
      dockerfile: kv-node/Dockerfile
    ports:
      - "8081:8080"
    container_name: worker1
    environment:
      - SPRING_PROFILES_ACTIVE=worker1
    networks:
      - app-network

  worker2:
    build:
      context: .
      dockerfile: kv-node/Dockerfile
    ports:
      - "8082:8080"
    container_name: worker2
    environment:
      - SPRING_PROFILES_ACTIVE=worker2
    networks:
      - app-network

networks:
  app-network:
    driver: bridge