version: '3.8'

services:
  leader:
    build:
      context: .
      dockerfile: kv-node/Dockerfile
    ports:
      - "8080:8080"
    container_name: leader
    environment:
      - PROFILE=leader
    networks:
      - app-network

  worker1:
    build:
      context: .
      dockerfile: kv-node/Dockerfile
    ports:
      - "8081:8080"
    container_name: worker1
    environment:
      - PROFILE=worker1
    networks:
      - app-network

  worker2:
    build:
      context: .
      dockerfile: kv-node/Dockerfile
    ports:
      - "8082:8080"
    container_name: worker2
    environment:
      - PROFILE=worker2
    networks:
      - app-network

networks:
  app-network:
    driver: bridge