server:
  port: 8084

spring:
  application:
    name: gateway
  cloud:
    consul:
      host: consul
      port: 8500
      discovery:
        prefer-ip-address: true
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: kv
          uri: lb://kv-node
          predicates:
            - Path=/kv/**
