server:
  port: ${PORT:0}  # overridden by Spring profile

spring:
  application:
    name: kv-node
  cloud:
    consul:
      host: consul
      port: 8500
      discovery:
        prefer-ip-address: true
        health-check-path: /actuator/health
        instance-id: ${spring.application.name}-${random.uuid}

management:
  endpoints:
    web:
      exposure:
        include: "*"